// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {RCFileType} {Win32\Debug\Project1_DRC.rc}

{$R 'Unit2.dfm' 'Form2:TForm'}
{$R 'Win32\Debug\Project1_DRC.res' 'Win32\Debug\Project1_DRC.rc'}

{$E CHS}

begin
end.
